### ISSUE TITLE
[Enhancement] Add badges in "Profile" page

### ISSUE THREAD

**Issue by Leo-Peyronnet** [Leo-Corporation/Gavilya#182]
### Enhancement

Add badges in "Profile" page: A new section will be added.

### Other informations

Add the following badges:

- [x] The Start (_Add a game_)
- [x] Crazy About It (_Mark a game as favorite_)
- [x] Need Space On The Shelves (_Have more than 50 games in your Library_)
- [x] Noob Player (_Play at least one hour, no matter which game_)
- [x] Starter Gamer (_Play at least 10 hours, no matter which game_)
- [x] Advanced Gamer (_Play at least 100 hours, no matter which game_)
- [x] True Gamer (_Play at least 1000 hours, no matter which game_)
- [x] Legendary Gamer (_Play at least 5000 hours, no matter which game_)
