### ISSUE TITLE
[Enhancement] Add a "First Run" experience

### ISSUE THREAD

**Issue by Leo-Peyronnet** [Leo-Corporation/Gavilya#35]
**Enhancement:**
Add a "First run" experience to Gavilya.

**Describe the solution:**
- [x] Add a window that introduce Gavilya
   - [x] Add the possibility to import a save file
   - [x] Add a tutorial/first run introduction

- [x] Add content to the pages that are empty 
    - [x] Home
    - [x] Recent Games
    - [x] Game List

**Comment by Leo-Peyronnet** [comment]
**Friday, December 19th**: The first run experience and all the above enhancements have been added to Gavilya. Closing issue
