### ISSUE TITLE
[Enhancement] Redesign the "GameInfoPage"

### ISSUE THREAD

**Issue by Leo-Peyronnet** [Leo-Corporation/Gavilya#50]
**Enhancement:**
Redesign the "GameInfoPage".

**Describe the solution:**
Add a new "panel" with:
- [x] The "Play" button
- [x] The last time played
- [x] The total time played
- [x] The current "Settings" button
- [x] A favorite button
