### ISSUE TITLE
[Enhancement] Add a "Statistics" page

### ISSUE THREAD

**Issue by Leo-Peyronnet** [Leo-Corporation/Gavilya#84]
**Enhancement:**
Add a "Statistics" page.

**Describe the solution:**
The "Statistics" page will show:

- [x] A bar chart showing the top ten most played games time (from lower to higher)
- [x] A complete list of all the user games from the most played to the least
- [x] A card recapitulating a game informations
     - [x] Last time played 
     - [x] Total time played
     - [x] Description of the game
- [x] An option allowing the user to change the order of the most played games (from least to most for instance)
